import setuptools

setuptools.setup(
    name="meta_arl",
    version="0.1dev",
    description="",
    # long_description=open("README.md").read(),
    url="https://github.com/david-lindner/meta-active-reward-learning",
    install_requires=[
        "absl_py",
        "argus==0.0.11",
        "config==0.5.1",
        "data-science-types==0.2.23",
        "gpytorch==1.6.0",
        "jsonpickle==1.5.2",
        "matplotlib==3.5.1",
        "mlflow==1.24.0",
        "mypy==0.982",
        "numpy==1.22.2",
        "pandas==1.4.1",
        "protobuf==3.20.0",
        "pyro_ppl==1.5.2",
        "PyYAML==6.0",
        "ray==1.10.0",
        "scikit_learn==1.1.1",
        "scipy==1.8.0",
        "setuptools==60.9.3",
        "stable_baselines3==1.5.0",
        "tensorboard==2.8.0",
        "torch==1.11.0",
    ],
    packages=setuptools.find_packages(),
    zip_safe=True,
    entry_points={},
)
